### PR TITLE
Update LICENSE.BSD

### PR DESCRIPTION
**Pull request by StevenAyr**
Added attribution to bring license in line with BSD 2 clause format.

### CODE REVIEW

**Comment by StevenAyr** [comment]
Went through and signed the CLA, please recheck.

**Comment by ariya** [comment]
I think the header of `esprima.js` needs to be adjusted as well? It would be weird if the two are not in sync.

**Comment by mikesherov** [comment]
Yes, there are a couple of BSD headers sprinkled throughout @StevenAyr can you get them all?

**Comment by StevenAyr** [comment]
I'm on it.

**Comment by StevenAyr** [comment]
Went through and updated all the BSD license headers. There are some in-line licenses that I assume apply just to particular contributed code that were not changed, and there are some other licenses in there that I'm going to go back and review, but all BSD licenses should now be up to date.

**Comment by ariya** [comment]
I think some of the third-part code (imported) should be touched (`test/3rdparty` mostly).

**Comment by ariya** [comment]
Also, it probably makes sense to do all the changes in just one commit.

**Comment by StevenAyr** [comment]
That makes sense. I'm running out but will put it all together tomorrow.

**Pull request closed without merging**
