### PR TITLE
Run Travis CI tests with Node.js 0.12 (stable) and io.js.

### PR DESCRIPTION
**Pull request by ariya**
See #1015.

### CODE REVIEW

**Comment by michaelficarra** [comment]
LGTM. Remove `0.8`?

**Comment by arthurvr** [comment]
I would remove 0.8 too, but no big deal for now. I'm wondering if [container based infrastructure using `sudo: false`](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) is an option for us, makes the build much faster.

**Comment by mathiasbynens** [comment]
:+1: to adding `sudo: false` for speedier builds.

**Comment by ikarienator** [comment]
:+1:

**Pull request closed without merging**
