### PR TITLE
Account for different possible arguments of a yield expression

### LINKED ISSUE #1469: a ? yield : b fails to parse
Try this code on http://esprima.org/demo/rewrite.html

``` javascript
function* gf() {
    var foo = false;
    return foo ? (yield* (yield)) : 10;
}
```

The first rewrite removes the parentheses around the `yield*` and `yield` expressions.  This produces syntactically invalid code which you can see by then pressing the rewrite button again, and esprima complains that an unexpected colon token was found.

### PR DESCRIPTION
**Pull request by ariya**
Fix #1469

### CODE REVIEW

**Comment by mikesherov** [comment]
Looks good except it's missing a test for `super`.

**Comment by mikesherov** [comment]
Also, not sure if we need a `yield yield` test?

**Comment by ariya** [comment]
> Also, not sure if we need a yield yield test?

For that, there exists already a test.

**Comment by ariya** [comment]
> Looks good except it's missing a test for super.

I'm still not sure what would be a good test for this. I speculate that we'll need it only once `isStartOfExpression` is being used for other purposes (than just parsing yield's argument).

**Comment by mikesherov** [comment]
Forgive me. Is this not a valid test of yield super?

```
class A extends B {
  *x() {
    yield super();
  }
}
```

**Comment by ariya** [comment]
@mikesherov Unfortunately not: `super` needs to be in a constructor (which can't be a generator).

**Comment by mikesherov** [comment]
@ariya here's a jsfiddle: https://jsfiddle.net/vwsrL6yL/

**Comment by ariya** [comment]
@mikesherov That looks like a good test, I'll add it. Thanks!

**Comment by mikesherov** [comment]
Once the test is added... :+1:

**Pull request closed without merging**
