### PR TITLE
Support rest parameter in arrow expression

### PR DESCRIPTION
**Pull request by ikarienator**
Related to #1011, #1012.

### CODE REVIEW

**Comment by ariya** [comment]
Typo: paramter -> parameter.

**Comment by ariya** [comment]
Is the reoder of `rest` property in the node intentional or a side effect of the implementation?

**Comment by ariya** [comment]
In `complex-rest-in-arrow-not-allowed.js`, there is no guarantee that the referred URL will be permanent. Might as well remove it or refer to the ES6 spec section.

**Comment by ikarienator** [comment]
@ariya The change of order is intentional. `rest` parameter shows up in the syntax before body.

**Comment by ikarienator** [comment]
The comment has been removed.

**Comment by mikesherov** [comment]
Great work! Once this is done and landed, we need to do the work of replacing defaults/rest properties with what's outlined in espree/espree#3. I can take that if needed.

LGTM

**Comment by mikesherov** [comment]
@ikarienator, can you make sure your commit message says:

```
Refs #1011
Refs #1012
```
?

Thanks!

**Comment by ariya** [comment]
With the minor change and commit message refs to the tickets, it's :+1:

**Comment by mikesherov** [comment]
:+1: from me, I'm going to land this.

**Pull request closed without merging**
