### PR TITLE
Introduce RestElement/AssignmentPattern as parameters instead of Function.rest and Function.defaults

### PR DESCRIPTION
**Pull request by mikesherov**

### CODE REVIEW

**Comment by ariya** [comment]
I thought we want to at least preserve `defaults` (as a transition step, see #1081), so that it's not a breaking change until 3.0.

Consider the following test (with no rest parameters) at all:

```js
require('./esprima').parse('function f(x=0){}').body[0]
```

With 2.0, we will have the following output:

```js
{ type: 'FunctionDeclaration',
  id: { type: 'Identifier', name: 'f' },
  params: [ { type: 'Identifier', name: 'x' } ],
  defaults: 
   [ { type: 'Literal',
       value: 0,
       raw: '0' } ],
  body: { type: 'BlockStatement', body: [] },
  rest: null,
  generator: false,
  expression: false }
```

With the change in this PR, it is going to be:

```js
{ type: 'FunctionDeclaration',
  id: { type: 'Identifier', name: 'f' },
  params: 
   [ { type: 'AssignmentPattern',
       left: [Object],
       right: [Object] } ],
  body: { type: 'BlockStatement', body: [] },
  generator: false,
  expression: false }
```

**Comment by mikesherov** [comment]
@ariya, meaning keep `defaults` as an empty array? or as an array of `undefined`? or keep the params as they were and make it additive?

**Comment by mikesherov** [comment]
@ariya, oh right. Defaults were in 2.0. I'll back out defaults change, and make this just be RestElement. Then we can discuss strategy for defaults in #1081

**Comment by mikesherov** [comment]
@ariya, I've updated the PR. @ikarienator @jeffmo can I get a review please? This is last blocker to 2.1

**Comment by mikesherov** [comment]
I've signed the CLA, probably just a timing issue that @scottgonzalez is working through. I'll ensure the commit message says `Closes #1011` when I land it.

**Comment by ariya** [comment]
LGTM :+1:

**Pull request merged**
