### PR TITLE
fixes #1120: support ES3 static member access restriction

### LINKED ISSUE #1120: missing name after . operator (esprima#4059)
When I try to evaluate esprima.js 2.1 with Rhino I get the message "missing name after . operator (esprima#4059)". Same code is working with esprima.js 2.0.
Same issue when using 2.1 release with the ANT task from https://github.com/ariya/ant-javascript-validate

### PR DESCRIPTION
**Pull request by michaelficarra**
Fixes #1120.

### CODE REVIEW

**Comment by mikesherov** [comment]
LGTM

**Comment by michaelficarra** [comment]
Unfortunately, this will be blocked by https://github.com/eslint/eslint/issues/2075.

**Comment by michaelficarra** [comment]
Should be good to go now with latest eslint release.

**Comment by nzakas** [comment]
Why was this blocked by an ESLint issue? ESLint doesn't use Esprima.

**Comment by mikesherov** [comment]
ESPrima uses eslint.

**Pull request closed without merging**
