### PR TITLE
Update latest TryStatement interface

### PR DESCRIPTION
**Pull request by Constellation**
See https://code.google.com/p/esprima/issues/detail?id=433

### CODE REVIEW

**Comment by cvrebert** [comment]
What's the status of this PR? It's been open for over a year.

**Comment by ariya** [comment]
See https://code.google.com/p/esprima/issues/detail?id=433#c5.

**Comment by mikesherov** [comment]
@cvrebert thanks for contributing, and please bear with us as we sort a few things out...

@ariya, looks like https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Parser_API now mentions "handler". Also, the mention Mozilla bug is fixed as of August: https://bugzilla.mozilla.org/show_bug.cgi?id=742612

Perhaps we can rebase this and land it, back compat concerns aside?

**Comment by ariya** [comment]
I think it's better to quickly check if there are tools broken by this. Otherwise, we have no data point.

A conservative approach is to emit both `handler` and `handlers`, slowly phasing out `handlers` in the process.

**Comment by ariya** [comment]
We are holding this off until 3.x, see #1030 for details.

**Pull request closed without merging**
