### PR TITLE
Separate API tests

### LINKED ISSUE #1422: Separate API tests
Consider that the API still continues to grow (most recently: tokenize delegate) and the current test runner is proven to be effective, it is about time that the tests for the API need to be separated from the rest of fixture-based syntax tests.

### PR DESCRIPTION
**Pull request by ariya**
Fixes #1422

### CODE REVIEW

**Comment by ariya** [comment]
Ah, Node.js 0.10 and 0.12 failed on this:

```js
/home/travis/build/jquery/esprima/test/api-tests.js:333
                [entry.type]: entry.value,
                ^
SyntaxError: Unexpected token [
```

**Comment by ariya** [comment]
> Ah, Node.js 0.10 and 0.12 failed on this:

This was fixed now.

**Comment by ariya** [comment]
I plan to land this in a day or two unless there is an objection.

**Comment by mikesherov** [comment]
:+1:

**Pull request closed without merging**
