### PR TITLE
Run the tests of downstream projects.

### PR DESCRIPTION
**Pull request by ariya**
This is done by checking out each project, run npm install, drop-in a
replacement for esprima.js, and run npm test. As of now, this is carried
out only as part of Travis CI build. It can be tested manually by:

```
  rm -rf downstream
  npm run downstream
```
Due to some unknown reason, .eslintrc can't exist otherwise it is going
to confuse the linting of the downstream project. The workaround is to
use custom config file.

Refs #1023

### CODE REVIEW

**Comment by ariya** [comment]
For some reasons, Travis CI complains with
```
npm ERR! notarget No compatible version found: esprima-moz@'*'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.0.0-dev-harmony-moz"]
```
when running `npm install` on Escodegen. This is weird, I can't reproduce it. Running `npm install esprima-moz@'*'` manually works just fine.

**Comment by ariya** [comment]
Until the mystery with escodegen is resolved, I've removed it and substituted with js2coffee for the time being.

**Comment by ariya** [comment]
Last status: build with io.js still fails, let me restart the build and see what happens.
Build time on Travis CI from 1.5 minutes to 8 minutes. Note that this is only executed for Node.js >= 0.11.

**Comment by ariya** [comment]
Travis CI is still failing. I'm going to restrict this downstream test run only to Node.js 0.12.

**Comment by ariya** [comment]
Any reviewer? @ikarienator @mikesherov

**Comment by mikesherov** [comment]
:eyes:

**Comment by mikesherov** [comment]
:+1:

**Pull request closed without merging**
