### PR TITLE
Add the support for token delegator.

### LINKED ISSUE #1332: API: Token delegator
A consumer might want to process a token as it is being produced by the tokenizer. This can be achieved by using the [delegation pattern](http://best-practice-software-engineering.ifs.tuwien.ac.at/patterns/delegation.html).

Note: this is related to `tokenize()` and not `parse()`.

### PR DESCRIPTION
**Pull request by ariya**
The third parameter to the `tokenize()` function is a callback function
that is invoked every time the tokenizer encounters a new token. The
return value of this callback function will be appended to the list of
tokens to be returned by `tokenize()`.

An example that returns ['answer', '=', '42']:

  esprima.tokenize('answer = 42', { range: true }, function (token) {
    return token.value;
  });

Fixes #1332

### CODE REVIEW

**Comment by ariya** [comment]
I finally discovered that it is easy enough to test the delegate: extend the existing test functionalities in `testTokenize`. It is simple and quite effective!

**Comment by ariya** [comment]
Also, the shuffling of properties in the test fixture is a harmless side effect (since we need not call `filterTokenLocation()` anymore after the tokenization is completed).

**Comment by michaelficarra** [comment]
No, this is even worse than I imagined. I strongly urge you to either use another strategy.

* conform to the ES6 iterator interface
* allow ES6 promises to be returned
* pass in another callback to the delegator callback for two-way async communication
* *anything* that is more powerful than a simple synchronous callback

**Comment by mikesherov** [comment]
@michaelficarra perhaps an explanation as to why this is so terrible, and an explanation of how your suggestions are more powerful?

**Comment by michaelficarra** [comment]
This doesn't allow lazily pulling tokens and it requires a synchronous delegator.

Let's say I only need to tokenise the first 10% of the file to find the token I want. I don't want to wait for esprima to tokenise the rest of the file to proceed.

Let's say I need to make an API call to determine how to handle a token. But I'm required to return a value immediately! How would I do this without another callback or a Promise return value?

**Comment by mikesherov** [comment]
> Let's say I only need to tokenise the first 10% of the file to find the token I want. I don't want to wait for esprima to tokenise the rest of the file to proceed.

Entirely possible with current implementation. You could pass a delegator to simply report on the tokens it's encountering. I don't need to wait for all of tokenization to finish.

Same goes for the async case, you could easily do async inside the delegator and ignore the return value of the tokenizer.

This implementation allows you to do whatever you want: provide transformers and rely on output of tokenize, or provide a callback if you need to do anything else special.

I'm not saying your solutions aren't more elegant, but I don't think the current implementation is bad and seems to be the most generic solution.

**Comment by michaelficarra** [comment]
Okay, I see. Yeah, this interface should be sufficient then. Thanks for explaining, @mikesherov.

**Comment by mikesherov** [comment]
:+1:

**Comment by ariya** [comment]
To be fair, the current design doesn't permit the tokenizer to abort. It still needs to process the entire source stream, though the delegator can choose to ignore the rest (if it is only interested in the first 10% tokens). As @michaelficarra mentioned, this is the limitation of such a simple, one-way synchronous callback.

For the record, the iterator-style API is still being planned. This is likely coming after the major surgery for the next 3.0. I'll probably file a separate issue to discuss that.

**Comment by mikesherov** [comment]
Can always `throw` in the delegate ;-). But yeah, by that point, we likely need a new API.

**Pull request closed without merging**
