### PR TITLE
Supports cover grammar related destructuring

### LINKED ISSUE #1045: ES6 feature: Destructuring: Tracking Issue
# [12.14.5](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-destructuring-assignment) Destructuring Assignment 

They are used in the left hand side of an assignment expression when `=` is the assignment operator, or at the `LeftHandSideExpression` position of a for-in or a for-of loop. 

Referred to by:
* [12.14.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-assignment-operators-static-semantics-early-errors) Static Semantics: Early Errors
* [13.6.4.1](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-for-in-and-for-of-statements-static-semantics-early-errors) Static Semantics: Early Errors

## Syntax:

<pre>
<i>AssignmentPattern</i>[Yield] :
  <i>ObjectAssignmentPattern</i><sub>[?Yield]</sub>
  <i>ArrayAssignmentPattern</i><sub>[?Yield]</sub>

<i>ObjectAssignmentPattern</i>[Yield] :
  <b>{</b> <b>}</b>
  <b>{</b> <i>AssignmentPropertyList</i><sub>[?Yield]</sub> <b>}</b>
  <b>{</b> <i>AssignmentPropertyList</i><sub>[?Yield]</sub> <b>,</b> <b>}</b>

<i>ArrayAssignmentPattern</i>[Yield] :
  <b>[</b> <i>Elision</i><sub>opt</sub> <i>AssignmentRestElement</i><sub>[?Yield]</sub><sub>opt</sub> <b>]</b>
  <b>[</b> <i>AssignmentElementList</i><sub>[?Yield]</sub> <b>]</b>
  <b>[</b> <i>AssignmentElementList</i><sub>[?Yield]</sub> , <i>Elision</i><sub>opt</sub> AssignmentRestElement</i><sub>[?Yield]</sub><sub>opt</sub> <b>]</b>

<i>AssignmentPropertyList</i>[Yield] :
  <i>AssignmentProperty</i><sub>[?Yield]</sub>
  <i>AssignmentPropertyList</i><sub>[?Yield]</sub> <b>,</b> <i>AssignmentProperty</i><sub>[?Yield]</sub>

<i>AssignmentElementList</i>[Yield] :
  <i>AssignmentElisionElement</i><sub>[?Yield]</sub>
  <i>AssignmentElementList<sub>[?Yield]</sub> <b>,</b> <i>AssignmentElisionElement</i><sub>[?Yield]</sub>

<i>AssignmentElisionElement</i>[Yield] :
  <i>Elision<sub>opt</sub> <i>AssignmentElement</i><sub>[?Yield]</sub>

<i>AssignmentProperty</i>[Yield] :
  <i>IdentifierReference</i><sub>[?Yield]</sub> <i>Initializer</i><sub>[In,?Yield]</sub><sub>opt</sub>
  <i>PropertyName</i> <b>:</b> <i>AssignmentElement</i><sub>[?Yield]</sub>

<i>AssignmentElement</i>[Yield] :
  <i>DestructuringAssignmentTarget</i><sub>[?Yield]</sub> <i>Initializer</i><sub>[In,?Yield]</sub><sub>opt</sub>

<i>AssignmentRestElement[Yield] :
  <b>...</b> <i>DestructuringAssignmentTarget</i><sub>[?Yield]</sub>

<i>DestructuringAssignmentTarget[Yield] :
  <i>LeftHandSideExpression</i><sub>[?Yield]</sub>
</pre>

## Spec:

Destructuring Assignment: https://people.mozilla.org/~jorendorff/es6-draft.html#sec-destructuring-assignment

Relevant AST interfaces (from https://github.com/estree/estree): (TBD)

## Early Errors:

<pre>
<i>AssignmentProperty</i> : <i>IdentifierReference</i> <i>Initializer</i><sub>opt</sub>
</pre>

* It is a Syntax Error if `IsValidSimpleAssignmentTarget` of `IdentifierReference` is `false`.

<pre>
<i>DestructuringAssignmentTarget</i> : <i>LeftHandSideExpression</i>
</pre>

* It is a Syntax Error if `LeftHandSideExpression` is either an `ObjectLiteral` or an `ArrayLiteral` and if the lexical token sequence matched by `LeftHandSideExpression` cannot be parsed with no tokens left over using `AssignmentPattern` as the goal symbol.

* It is a Syntax Error if `LeftHandSideExpression` is neither an `ObjectLiteral` nor an `ArrayLiteral` and `IsValidSimpleAssignmentTarget(LeftHandSideExpression)` is `false`.

# [13.2.3](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-destructuring-binding-patterns) Destructuring Binding Patterns

`BindingPattern`s are used in `LexicalBinding`s, `VariableDeclaration`s, `ForBinding`s and `CatchParameter`s. `BindingElement` is also used in `FormalParameter`s. A `BindingElement` is either a `BindingPattern` or a `BindingIdentifier`, optionally followed by a `Initializer`.

## Syntax

<pre>
<i>BindingPattern</i><sub>[Yield,GeneratorParameter]</sub> :
  <i>ObjectBindingPattern</i><sub>[?Yield,?GeneratorParameter]</sub>
  <i>ArrayBindingPattern</i><sub>[?Yield,?GeneratorParameter]</sub>

<i>ObjectBindingPattern</i><sub>[Yield,GeneratorParameter]</sub> :
  <b>{</b> <b>}</b>
  <b>{</b> <i>BindingPropertyList</i><sub>[?Yield,?GeneratorParameter]</sub> <b>}</b>
  <b>{</b> <i>BindingPropertyList</i><sub>[?Yield,?GeneratorParameter]</sub> <b>,</b> <b>}</b>

<i>ArrayBindingPattern</i><sub>[Yield,GeneratorParameter]</sub> :
  <b>[</b> <i>Elision</i><sub>opt</sub> <i>BindingRestElement</i><sub>[?Yield, ?GeneratorParameter]</sub><sub>opt</sub> <b>]</b>
  <b>[</b> <i>BindingElementList</i><sub>[?Yield, ?GeneratorParameter]</sub> <b>]</b>
  <b>[</b> <i>BindingElementList</i><sub>[?Yield, ?GeneratorParameter]</sub> <b>,</b> <i>Elision</i><sub>opt</sub> <i>BindingRestElement</i><sub>[?Yield, ?GeneratorParameter]</sub><sub>opt</sub> <b>]</b>

<i>BindingPropertyList</i><sub>[Yield,GeneratorParameter]</sub> :
  <i>BindingProperty</i><sub>[?Yield, ?GeneratorParameter]</sub>
  <i>BindingPropertyList</i><sub>[?Yield, ?GeneratorParameter]</sub> <b>,</b> <i>BindingProperty</i><sub>[?Yield, ?GeneratorParameter]</sub>

<i>BindingElementList</i><sub>[Yield,GeneratorParameter]</sub> :
  <i>BindingElisionElement</i><sub>[?Yield, ?GeneratorParameter]</sub>
  <i>BindingElementList</i><sub>[?Yield, ?GeneratorParameter]</sub> <b>,</b> <i>BindingElisionElement</i><sub>[?Yield, ?GeneratorParameter]</sub>

<i>BindingElisionElement</i><sub>[Yield,GeneratorParameter]</sub> :
  <i>Elision</i><sub>opt</sub> <i>BindingElement</i><sub>[?Yield, ?GeneratorParameter]</sub>

<i>BindingProperty</i><sub>[Yield,GeneratorParameter]</sub> :
  <i>SingleNameBinding</i><sub>[?Yield, ?GeneratorParameter]</sub>
  <i>PropertyName</i><sub>[?Yield, ?GeneratorParameter]</sub> <b>:</b> <i>BindingElement</i><sub>[?Yield, ?GeneratorParameter]</sub>

<i>BindingElement</i><sub>[Yield,GeneratorParameter]</sub> :
  <i>SingleNameBinding</i><sub>[?Yield, ?GeneratorParameter]</sub>
  [+GeneratorParameter] <i>BindingPattern</i><sub>[?Yield,GeneratorParameter]</sub> <i>Initializer</i><sub>[In]</sub><sub>opt</sub>
  [~GeneratorParameter] <i>BindingPattern</i><sub>[?Yield]</sub> <i>Initializer</i><sub>[In, ?Yield]</sub><sub>opt</sub>

<i>SingleNameBinding</i> <sub>[Yield, GeneratorParameter]</sub> :
  [+GeneratorParameter] <i>BindingIdentifier</i><sub>[Yield]</sub> <i>Initializer</i><sub>[In]</sub><sub>opt</sub>
  [~GeneratorParameter] <i>BindingIdentifier</i><sub>[?Yield]</sub> <i>Initializer</i><sub>[In, ?Yield]</sub><sub>opt</sub>

<i>BindingRestElement</i><sub>[Yield, GeneratorParameter]</sub> :
  [+GeneratorParameter] <b>...</b> <i>BindingIdentifier</i><sub>[Yield]</sub>
  [~GeneratorParameter] <b>...</b> <i>BindingIdentifier</i><sub>[?Yield]</sub>

</pre>

## Spec

Destructuring Binding Patterns: https://people.mozilla.org/~jorendorff/es6-draft.html#sec-destructuring-binding-patterns

Relevant AST interfaces (from https://github.com/estree/estree): (TBD)

#### SpiderMonkey AST

```idl
interface ObjectPattern <: Pattern {
    type: "ObjectPattern";
    properties: [ { key: Literal | Identifier, value: Pattern } ];
}

interface ArrayPattern <: Pattern {
    type: "ArrayPattern";
    elements: [ Pattern | null ];
}
```

#### Shift AST

```webidl
typedef (ObjectBinding or ArrayBinding or BindingIdentifier or MemberExpression) Binding;


interface BindingWithDefault : Node {
  attribute (ObjectBinding or ArrayBinding or BindingIdentifier) binding;
  attribute Expression init;
};

interface BindingIdentifier : Node {
  attribute Identifier identifier;
};

interface ArrayBinding : Node {
  attribute (Binding or BindingWithDefault)?[] elements;
  attribute BindingIdentifier? restElement;
};

interface ObjectBinding : Node {
  attribute BindingProperty[] properties;
};

interface BindingProperty : Node { };

interface BindingPropertyIdentifier : BindingProperty {
  attribute BindingIdentifier identifier;
  attribute Expression? init;
};

interface BindingPropertyProperty : BindingProperty {
  attribute PropertyName name;
  attribute (Binding or BindingWithDefault) binding;
};


interface PropertyName : Node { };

interface ComputedPropertyName : PropertyName {
  attribute Expression value;
};

interface StaticPropertyName : PropertyName {
  attribute string value;
};

```

## Related Tasks:

- [ ] Destructuring default #1028 (previous [issue 565](https://code.google.com/p/esprima/issues/detail?id=565))
- [ ] Previous [issue 489](https://code.google.com/p/esprima/issues/detail?id=489)
- [x] [Step 1](https://github.com/jquery/esprima/issues/1118)

### LINKED ISSUE #1060: Patterns in for in / of statements
kamicane wrote in https://code.google.com/p/esprima/issues/detail?id=558

This is on the harmony branch.

This does not parse for for in / of statements:

    for ([a,b] in x) a;
    for ([a,b] of x) a;
    for ({a,b} in x) a;
    for ({a,b} of x) a;

Same for comprehensions:

    [for ([a,b] of x) a];

Esprima errors out with:

   Invalid left-hand side in for-in

for for in statements, and it parses the ArrayPattern / ObjectPattern as ArrayExpression / ObjectExpression in for of statements, while it should maybe probably be:

    "type": "ForInStatement",
    "left": {
      "type": "ArrayPattern"

This is the tree i tested on:

https://github.com/ariya/esprima/tree/f1b3150aa43205d511e3452b8c1cead96d2925d4

### PR DESCRIPTION
**Pull request by ikarienator**
Closes #1045.
Related to #1060.

### CODE REVIEW

**Comment by mikesherov** [comment]
Woah. Looks good so far from what I can tell. Some of the test files have a misspelling of `patter` instead of `pattern` and this doesn't actually close #1060 until we bring this back to the harmony branch.

**Comment by ikarienator** [comment]
I think it does close #1060 because the destructuring in for in loop will be supported in this PR as well.

**Comment by ikarienator** [comment]
@mikesherov I believe the attached test cases are actually more thorough than espree. @nzakas can you help review the tests?

**Comment by ariya** [comment]
LGTM :+1:

**Comment by mikesherov** [comment]
@ikarienator LGTM but this can't close #1060 until all of the work is back ported to the harmony branch as well.

Also, please address the test files that have a misspelling of `patter` instead of `pattern`.

Great work here!

**Comment by nzakas** [comment]
Yeah, tests are definitely covering more edge cases. :+1:

**Comment by ikarienator** [comment]
Amended it! Thanks guys for the review!

**Comment by ikarienator** [comment]
Before:

| Case | Size | Benchmark |
|:-----:|:----:|----------:|
|    Underscore 1.5.2 |   42.5 KiB  |   4.16 ms ± 1.10%  |
|      Backbone 1.1.0 |   58.7 KiB  |   4.20 ms ± 0.87%  |
|      MooTools 1.4.5 |  156.7 KiB  |  21.88 ms ± 0.81%  |
|        jQuery 1.9.1 |  262.1 KiB  |  21.80 ms ± 0.90%  |
|          YUI 3.12.0 |  330.4 KiB  |  23.16 ms ± 2.62%  |
| jQuery.Mobile 1.4.2 |  442.2 KiB  |  67.39 ms ± 2.57%  |
|       Angular 1.2.5 |  701.7 KiB  |  46.06 ms ± 2.63%  |
|             Summary | 1994.3 KiB  | 188.66 ms ± 2.26%  |

After:

| Case | Size | Benchmark |
|:-----:|:----:|----------:|
|    Underscore 1.5.2 |   42.5 KiB  |   4.94 ms ± 4.02%  |
|      Backbone 1.1.0 |   58.7 KiB  |   4.24 ms ± 0.76%  |
|      MooTools 1.4.5 |  156.7 KiB  |  22.24 ms ± 0.87%  |
|        jQuery 1.9.1 |  262.1 KiB  |  22.65 ms ± 0.77%  |
|          YUI 3.12.0 |  330.4 KiB  |  23.36 ms ± 2.98%  |
| jQuery.Mobile 1.4.2 |  442.2 KiB  |  62.07 ms ± 4.46%  |
|       Angular 1.2.5 |  701.7 KiB  |  48.55 ms ± 2.15%  |
|             Summary | 1994.3 KiB  | 188.04 ms ± 3.08%  |

It looks like that the performance impact is insignificant.

**Comment by ariya** [comment]
@ikarienator Nice benchmark numbers :smile:

**Pull request closed without merging**
