### PR TITLE
More conditional Zs check

### PR DESCRIPTION
**Pull request by klaiderklai**
Sorry for editing this from Github's editor, but the repository is heavy to easily fork.

### CODE REVIEW

**Comment by michaelficarra** [comment]
Why?

**Comment by klaiderklai** [comment]
@michaelficarra So why not?

**Comment by michaelficarra** [comment]
In order to accept a PR with no functionality changes, the maintainers will need to know what makes it better. It is not clear to me that this is better. In fact, it looks worse.

**Comment by klaiderklai** [comment]
@michaelficarra ........................... Look it yourself and you'll understand. The unique objective is to reduce how many code points will be compared.

**Comment by klaiderklai** [comment]
@michaelficarra If you're not satisfied with life, get out

**Comment by klaiderklai** [comment]
@michaelficarra You're the coffeescript shit, that looks it. Some shit like you would end with ECMA-262 4th edition, bcuz you're stupid! Worthless!

**Comment by klaiderklai** [comment]
You're a worthless stupid clown! If you know nothing about ES, then get out

**Comment by klaiderklai** [comment]
@michaelficarra Your "transpiler" language is a shit. I'd do better, I'd build a kind of VM inside JS instead of just transpiling, and that's what I'll do when I finish the language lexer and etc. I made, made and re-made the UTF-8 decoder and will redo UTF-16 decoder, and other helpers.

**Comment by klaiderklai** [comment]
@michaelficarra You're very unqualified to get near ECMA-262.

**Comment by klaiderklai** [comment]
@michaelficarra  And just for your information, my language will be based on ECMA-262-4, and will be specified! You're not able to do anything major than this.

**Comment by klaiderklai** [comment]
@michaelficarra You're a lazy idiot, dumb spaghetti.

**Comment by klaiderklai** [comment]
And my language will be functionally compiled to ES3 (using from JavaScript), no hackish.

**Comment by mikesherov** [comment]
Verbal abuse of any kind is not welcome here. Locking this thread, and blocking you from this repo. Feel free to reach out to me personally if you feel this was the wrong action to take.

**Comment by mikesherov** [comment]
On second thought, I won't block you from the repo, but please consider this as a warning that abuse is not tolerated.

**Pull request closed without merging**
