### PR TITLE
Simplify punctuator scanning.

### LINKED ISSUE #1072: Simplify punctuator scanning
Currently `scanPunctuator()` is quite long and unnecessarily complex. Refactoring this function to be less repetitive will lead to a more readable implementation.

### PR DESCRIPTION
**Pull request by ariya**
Reduce the amount of repetition. Consistently use character check
instead of character code throughout the function.
No performance increase or regression was observed.

Closes #1072

### CODE REVIEW

**Comment by ariya** [comment]
`scanPunctuator()` is now about half the size, but hopefully more readable :yum:

**Comment by ikarienator** [comment]
Can we have the performance number posted here?

**Comment by ariya** [comment]
Before:
```
    Underscore 1.5.2    42.5 KiB      6.72 ms ± 2.31%
      Backbone 1.1.0    58.7 KiB      6.46 ms ± 2.28%
      MooTools 1.4.5   156.7 KiB     32.71 ms ± 2.59%
        jQuery 1.9.1   262.1 KiB     36.45 ms ± 2.92%
          YUI 3.12.0   330.4 KiB     34.36 ms ± 2.97%
 jQuery.Mobile 1.4.2   442.2 KiB    104.96 ms ± 9.62%
       Angular 1.2.5   701.7 KiB     73.81 ms ± 4.99%
                     ------------------------
                      1994.3 KiB    295.46 ms ± 6.49%
```

After:
```
    Underscore 1.5.2    42.5 KiB      7.32 ms ± 2.88%
      Backbone 1.1.0    58.7 KiB      6.79 ms ± 2.55%
      MooTools 1.4.5   156.7 KiB     33.96 ms ± 2.15%
        jQuery 1.9.1   262.1 KiB     35.58 ms ± 2.61%
          YUI 3.12.0   330.4 KiB     35.53 ms ± 3.22%
 jQuery.Mobile 1.4.2   442.2 KiB    106.57 ms ± 5.85%
       Angular 1.2.5   701.7 KiB     77.06 ms ± 6.21%
                     ------------------------
                      1994.3 KiB    302.81 ms ± 4.98%
```

(V8 shell 3.22)

**Comment by ikarienator** [comment]
AWESOME! :+1:

**Pull request merged**
