### PR TITLE
Adds missing parenthesis

### PR DESCRIPTION
**Pull request by mariusschulz**
;)

### CODE REVIEW

**Comment by ariya** [comment]
@mariusschulz Fancy signing the CLA?

**Comment by mariusschulz** [comment]
@ariya Sorry, of course—that must have slipped by me. I've signed the CLA now. How do I re-trigger Travis?

**Comment by ariya** [comment]
I think the CLA check needs to be retriggered, now Travis. Do you mind closing the pull request and create another one so that the CLA checker runs again?

**Comment by michaelficarra** [comment]
Rebasing should do it. If it doesn't, that's a problem that needs to be fixed.

**Comment by mariusschulz** [comment]
Done, here you go: https://github.com/jquery/esprima/pull/1260

**Comment by michaelficarra** [comment]
Ugh, no.

**Comment by mariusschulz** [comment]
Rebasing would require a force-push, if I'm not missing anything here. Travis would pick that up, right?

**Comment by michaelficarra** [comment]
Yes, and then we wouldn't have duplicate pull requests lying around. It pollutes search and splits up conversation.

**Comment by mariusschulz** [comment]
That makes sense. I'll keep it in mind for next time!

**Pull request closed without merging**
