### PR TITLE
Adjust the error message for missing const initializer

### LINKED ISSUE #1547: Adjust the error message for missing const initializer
Since we tend to follow V8/Node.js, a missing initializer for `const` needs to have a similar error message.

Test case:
```js
esprima.parse('const x;')
```

Actual:
```
Error: Line 1: Unexpected token ;
```

Expected (just as V8):
```
Error: Line 1: Missing initializer in const declaration
```

### PR DESCRIPTION
**Pull request by ariya**
Fixes #1547

### CODE REVIEW

**Comment by ariya** [comment]
Whoa, the downstream test failed because one of recast's test relies on the old error message. I need to investigate...

**Comment by mikesherov** [comment]
:+1:

**Comment by mikesherov** [comment]
As an aside, it would be nice if failure messages were JSON pretty printed like they were during the initial conversion.

**Comment by ariya** [comment]
> As an aside, it would be nice if failure messages were JSON pretty printed...

At some point, we need to normalize those failure reports anyway (#1272).

**Comment by ariya** [comment]
Oh, it's too bad that the workaround for recast hard-coded test worked in this pull request but it doesn't work after it's merged to master 😿

**Pull request closed without merging**
