### PR TITLE
Implement SuperProperty.

### LINKED ISSUE #1147: Implement `Super` Node
As per https://github.com/estree/estree/pull/57

### PR DESCRIPTION
**Pull request by ariya**
Closes #1147.

### CODE REVIEW

**Comment by ariya** [comment]
Just the basics for now, no early error and such.

**Comment by nzakas** [comment]
Lgtm

**Comment by mikesherov** [comment]
:+1:

**Comment by ikarienator** [comment]
You must check that `super` is directly followed by `(`(in `parseLeftHandSideExpressionAllowCall`), `.` or `[`. super access can only happen in a function and super call can only happen in a constructor of a class that has extends clause.

**Comment by matthewaveryusa** [comment]
This is great thanks!

**Comment by ariya** [comment]
@ikarienator Updated to account for your review. This however doesn't address the extends clause (deliberate for now, to get something in quickly first).

**Pull request closed without merging**
