### PR TITLE
Use identifier categories from Unicode 8.0.0

### LINKED ISSUE #1475: Use the most recent Unicode 8.0
According to http://www.unicode.org/versions/Unicode8.0.0/, Unicode 8 has been released in June 2015.

ES2016 is going to require Unicode 8.0.0: https://github.com/tc39/ecma402/pull/72.

### PR DESCRIPTION
**Pull request by ariya**
Fixes #1475

### CODE REVIEW

**Comment by michaelficarra** [comment]
Whitespace characters (category `Zs`) also changed between Unicode 5 and Unicode 8. The regex may need to be updated.

**Comment by mathiasbynens** [comment]
@michaelficarra `Zs` is not used in `tools/generate-identifier-regex.js` so this patch LGTM.

**Comment by michaelficarra** [comment]
@mathiasbynens What I'm saying is it should be. There's a hardcoded regex on [line 24](https://github.com/jquery/esprima/pull/1476/files#diff-0a4138c56827157a6b8e5f1136e69950R24).

**Comment by mathiasbynens** [comment]
@michaelficarra There’s also `isWhitespace`. Sounds like we agree; I just those changes belong in a separate pull request.

**Comment by mathiasbynens** [comment]
Aah, we’re talking about the same thing. (I was confused because you mentioned a regex.)

**Comment by michaelficarra** [comment]
@mathiasbynens Sorry, yeah it's just a list of code points. Either way, I think the upgrades to Unicode 8 should all happen in the same PR/commit.

**Comment by mathiasbynens** [comment]
```diff
diff --git a/src/character.ts b/src/character.ts
index 8ddadf3..3a2679e 100644
--- a/src/character.ts
+++ b/src/character.ts
@@ -19,7 +19,7 @@ export const Character = {
 
     isWhiteSpace(cp: number): boolean {
         return (cp === 0x20) || (cp === 0x09) || (cp === 0x0B) || (cp === 0x0C) || (cp === 0xA0) ||
-            (cp >= 0x1680 && [0x1680, 0x180E, 0x2000, 0x2001, 0x2002, 0x2003, 0x2004, 0x2005, 0x2006, 0x2007, 0x2008, 0x2009, 0x200A, 0x202F, 0x205F, 0x3000, 0xFEFF].indexOf(cp) >= 0);
+            (cp >= 0x1680 && [0x1680, 0x2000, 0x2001, 0x2002, 0x2003, 0x2004, 0x2005, 0x2006, 0x2007, 0x2008, 0x2009, 0x200A, 0x202F, 0x205F, 0x3000, 0xFEFF].indexOf(cp) >= 0);
     },
 
     // ECMA-262 11.3 Line Terminators
```

**Comment by ariya** [comment]
@michaelficarra Good point!
@mathiasbynens I'll amend the commit with the removal of 0x180E in whitespace.

Thanks for the review folks!

**Comment by ariya** [comment]
The failing downstream test is from `redeyed`. It does run a smoke test on some JavaScript source files that still assume U+180E as a whitespace. This is addressed in https://github.com/thlorenz/redeyed/pull/5.

**Comment by ariya** [comment]
Just to clarify, the failing downstream test is a false positive. It is not an indication that the changeset in this pull request is the problem.

**Comment by mikesherov** [comment]
I still find it amazing @ariya that you take the time to submit PRs to all the downstream problems whenever there is a failing test.

**Comment by ariya** [comment]
Thanks @mikesherov! Sometimes those projects are too important to be ignore :smile_cat:

**Pull request closed without merging**
