### PR TITLE
Adding CDN usage + appropriate warnings.

### PR DESCRIPTION
**Pull request by rdodev**
Ariya,

As per our conversation in the google code issue, here's the PR for your review.

Google Code issue: https://code.google.com/p/esprima/issues/detail?id=627

### CODE REVIEW

**Comment by ariya** [comment]
Still no link to the issue in the commit message. Also, the URL should now point to `jquery/esprima`.

**Comment by rdodev** [comment]
Oh ... did not see the change to the jquery github org. Will add link to issue in the commit message.

**Comment by ariya** [comment]
Any reason why this is becoming two commits again? Anyhow, I will just squash them manually.

**Comment by ariya** [comment]
Landed. Thanks!

**Pull request closed without merging**
