### PR TITLE
disable early errors in Shift parser in speed comparison

### PR DESCRIPTION
**Pull request by michaelficarra**

### CODE REVIEW

**Comment by ariya** [comment]
I'm undecided about this. Other parsers don't have such a distinction, there are valid different use cases in reporting errors vs skipping them. I think most likely we need two different benchmarks for each case.

**Comment by mikesherov** [comment]
I concur. 2 separate benchs seems to make sense to me.

On Wed, Apr 29, 2015 at 12:15 PM, Ariya Hidayat <notifications@github.com>
wrote:

> I'm undecided about this. Other parsers don't have such a distinction,
> there are valid different use cases in reporting errors vs skipping them. I
> think most likely we need two different benchmarks for each case.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/jquery/esprima/pull/1166#issuecomment-97485079>.
>



-- 
Mike Sherov

**Comment by michaelficarra** [comment]
My argument is that we should use whatever mode gives a result the fastest for a known valid program. So for Acorn, we should be using `parse_dammit`.

**Comment by ariya** [comment]
Close this in favor of Shift in both modes (which I'll implement shortly).

**Pull request closed without merging**
