### PR TITLE
fix #1829, returnstatement with multiline template literal string

### LINKED ISSUE #1829: ReturnStatement parse bug when code like "return `\nabc`;"
### Steps to reproduce

code1:
```
function a(){
  return `\na`;
}
```
code2:
```
function a(){
  return `
a`;
}
```

```js
let ast1 = esprima.parse(code1);
let ast2 = esprima.parse(code2);
```
### Expected output

 both v3.1.3 and v4.0.0-dev  have the same output
``` 
// ast1， it's fine ,  ReturnStatement with correct argument property
{
    "type": "Program",
    "body": [
        {
            "type": "FunctionDeclaration",
            "id": {
                "type": "Identifier",
                "name": "a"
            },
            "params": [],
            "body": {
                "type": "BlockStatement",
                "body": [
                    {
                        "type": "ReturnStatement",
                        "argument": {
                            "type": "TemplateLiteral",
                            "quasis": [
                                {
                                    "type": "TemplateElement",
                                    "value": {
                                        "raw": "\\na",
                                        "cooked": "\na"
                                    },
                                    "tail": true
                                }
                            ],
                            "expressions": []
                        }
                    }
                ]
            },
            "generator": false,
            "expression": false
        }
    ],
    "sourceType": "script"
}
//  ast2  it is wrong , function body should only contain single node : ReturnStatement
//           but the following ast  have  ExpressionStatement after ReturnStatement,  and ReturnStatement.argument is null
{
    "type": "Program",
    "body": [
        {
            "type": "FunctionDeclaration",
            "id": {
                "type": "Identifier",
                "name": "a"
            },
            "params": [],
            "body": {
                "type": "BlockStatement",
                "body": [
                    {
                        "type": "ReturnStatement",
                        "argument": null
                    },
                    {
                        "type": "ExpressionStatement",
                        "expression": {
                            "type": "TemplateLiteral",
                            "quasis": [
                                {
                                    "type": "TemplateElement",
                                    "value": {
                                        "raw": "\na",
                                        "cooked": "\na"
                                    },
                                    "tail": true
                                }
                            ],
                            "expressions": []
                        }
                    }
                ]
            },
            "generator": false,
            "expression": false
        }
    ],
    "sourceType": "script"
}
```

### PR DESCRIPTION
**Pull request by fishbar**

### CODE REVIEW

**Comment by johnjbarton** [comment]
I think the file migrated_0004.tree.json needs to be

```js
{
    "range": [
        0,
        41
    ],
    "loc": {
        "start": {
            "line": 1,
            "column": 0
        },
        "end": {
            "line": 5,
            "column": 1
        }
    },
    "type": "Program",
    "body": [
        {
            "range": [
                0,
                41
            ],
            "loc": {
                "start": {
                    "line": 1,
                    "column": 0
                },
                "end": {
                    "line": 5,
                    "column": 1
                }
            },
            "type": "FunctionDeclaration",
            "id": {
                "range": [
                    9,
                    10
                ],
                "loc": {
                    "start": {
                        "line": 1,
                        "column": 9
                    },
                    "end": {
                        "line": 1,
                        "column": 10
                    }
                },
                "type": "Identifier",
                "name": "a"
            },
            "params": [],
            "body": {
                "range": [
                    13,
                    41
                ],
                "loc": {
                    "start": {
                        "line": 1,
                        "column": 13
                    },
                    "end": {
                        "line": 5,
                        "column": 1
                    }
                },
                "type": "BlockStatement",
                "body": [
                    {
                        "range": [
                            17,
                            23
                        ],
                        "loc": {
                            "start": {
                                "line": 2,
                                "column": 2
                            },
                            "end": {
                                "line": 2,
                                "column": 8
                            }
                        },
                        "type": "ReturnStatement",
                        "argument": null
                    },
                    {
                        "range": [
                            24,
                            39
                        ],
                        "loc": {
                            "start": {
                                "line": 2,
                                "column": 9
                            },
                            "end": {
                                "line": 4,
                                "column": 4
                            }
                        },
                        "type": "ExpressionStatement",
                        "expression": {
                            "range": [
                                24,
                                38
                            ],
                            "loc": {
                                "start": {
                                    "line": 2,
                                    "column": 9
                                },
                                "end": {
                                    "line": 4,
                                    "column": 3
                                }
                            },
                            "type": "TemplateLiteral",
                            "quasis": [
                                {
                                    "range": [
                                        24,
                                        38
                                    ],
                                    "loc": {
                                        "start": {
                                            "line": 2,
                                            "column": 9
                                        },
                                        "end": {
                                            "line": 4,
                                            "column": 3
                                        }
                                    },
                                    "type": "TemplateElement",
                                    "value": {
                                        "raw": "\n    test\n  ",
                                        "cooked": "\n    test\n  "
                                    },
                                    "tail": true
                                }
                            ],
                            "expressions": []
                        }
                    }
                ]
            },
            "generator": false,
            "expression": false,
            "async": false
        }
    ],
    "sourceType": "script",
    "tokens": [
        {
            "range": [
                0,
                8
            ],
            "loc": {
                "start": {
                    "line": 1,
                    "column": 0
                },
                "end": {
                    "line": 1,
                    "column": 8
                }
            },
            "type": "Keyword",
            "value": "function"
        },
        {
            "range": [
                9,
                10
            ],
            "loc": {
                "start": {
                    "line": 1,
                    "column": 9
                },
                "end": {
                    "line": 1,
                    "column": 10
                }
            },
            "type": "Identifier",
            "value": "a"
        },
        {
            "range": [
                10,
                11
            ],
            "loc": {
                "start": {
                    "line": 1,
                    "column": 10
                },
                "end": {
                    "line": 1,
                    "column": 11
                }
            },
            "type": "Punctuator",
            "value": "("
        },
        {
            "range": [
                11,
                12
            ],
            "loc": {
                "start": {
                    "line": 1,
                    "column": 11
                },
                "end": {
                    "line": 1,
                    "column": 12
                }
            },
            "type": "Punctuator",
            "value": ")"
        },
        {
            "range": [
                13,
                14
            ],
            "loc": {
                "start": {
                    "line": 1,
                    "column": 13
                },
                "end": {
                    "line": 1,
                    "column": 14
                }
            },
            "type": "Punctuator",
            "value": "{"
        },
        {
            "range": [
                17,
                23
            ],
            "loc": {
                "start": {
                    "line": 2,
                    "column": 2
                },
                "end": {
                    "line": 2,
                    "column": 8
                }
            },
            "type": "Keyword",
            "value": "return"
        },
        {
            "range": [
                24,
                38
            ],
            "loc": {
                "start": {
                    "line": 2,
                    "column": 9
                },
                "end": {
                    "line": 4,
                    "column": 3
                }
            },
            "type": "Template",
            "value": "`\n    test\n  `"
        },
        {
            "range": [
                38,
                39
            ],
            "loc": {
                "start": {
                    "line": 4,
                    "column": 3
                },
                "end": {
                    "line": 4,
                    "column": 4
                }
            },
            "type": "Punctuator",
            "value": ";"
        },
        {
            "range": [
                40,
                41
            ],
            "loc": {
                "start": {
                    "line": 5,
                    "column": 0
                },
                "end": {
                    "line": 5,
                    "column": 1
                }
            },
            "type": "Punctuator",
            "value": "}"
        }
    ]
}
```

**Comment by johnjbarton** [comment]
Now I think that this PR is not successful.  I could not get the equivalent code to work for our case. Then I looked at the AST produced by the online demo and compared it to the test result above.  It's clear that the result from the test:
```
                        "type": "ReturnStatement",
                        "argument": null
```
means the patch failed: the Template is being parsed as an ExpressionStatement not as an Expression argument of the ReturnStatement.  There will be `null` as the return value in the execution.

AFAICT, `this.match('`')` is never true. So I guess that is not the way to detect a Template start. The scanner has special template logic so maybe the Template is a special token.

The underlying bug means we can't use template literals in return statements in a natural way.

**Comment by johnjbarton** [comment]
PR #1882 has an alternative fix that works on our code.

**Comment by ariya** [comment]
Superced by #1882.

**Pull request closed without merging**
