### PR TITLE
Extend ExpressionStatement to indicate a directive prologue

### PR DESCRIPTION
**Pull request by jasonLaster**
Refs #1006 

Started a WIP PR for 'use strict' directives. This is pending estree/estree#6, but in the meantime I have two questions:

1. does the change belong in `finishExpresionStatement` or should we be passing more metadata down like a strict flag?
2. what's the best way to update the tests? will we run into the same problem as before?

### CODE REVIEW

**Comment by ariya** [comment]
It's definitely not just inside `finishExpresionStatement`, not every 'use strict' expression magically becomes a directive. Take a look at e.g. `parseScriptBody` where such a directive is detected.

**Comment by jasonLaster** [comment]
@ariya  oy, sloppy. I'll revisit soon.

**Comment by michaelficarra** [comment]
Also, all directives need this property, not just `use strict` directives.

**Comment by ariya** [comment]
Seems that we want to hold this off since the discussion on ESTree is not coming to a consensus.

**Comment by ariya** [comment]
Per the discussion (here and on IRC), let's close this now and reopen again once we get more consensus on ESTree and a refined directive implementation.

**Pull request closed without merging**
