### PR TITLE
Properly allow or prohibit `let` in a binding identifier/pattern.

### LINKED ISSUE #1048: "var let" should be allowed in non-strict mode
**What steps will reproduce the problem?**

```js
esprima.parse("var let")
```

**What is the expected output?** No error

**What do you see instead?** `Unexpected token let`

**What version of the product are you using? On what operating system? Which
browser?** All versions of esprima after https://github.com/ariya/esprima/commit/2b4bdb04ec#diff-7c9336e4324ea31118ce749be055b6a3R311 was committed

**Please provide any additional information below.**

`let` is tricky, it's not a keyword in ES5 or ES6. In strict mode esprima should complain about it, but in non-strict mode `var let` should be fine. The ES6 spec has a few places where `let` is banned even in non-strict mode (see the note on https://people.mozilla.org/~jorendorff/es6-draft.html#sec-keywords ), but this does not include var declarations.

There is currently a test to make sure that "var let" is an error. This test should make sure that it is not an error instead: https://github.com/ariya/esprima/blob/master/test/test.js#L22252

(Migrated from https://code.google.com/p/esprima/issues/detail?id=588, as filed by @gabelevi)

### PR DESCRIPTION
**Pull request by ariya**
Fixes #1048
Refs #1098

### CODE REVIEW

**Comment by ariya** [comment]
Unless there is an objection, I will probably land this pretty soon.

**Comment by michaelficarra** [comment]
Let me review first.

**Comment by ariya** [comment]
> Let me review first.

Sure thing.

**Comment by michaelficarra** [comment]
Seems good. I'm going to open an issue for allowing `let` as an identifier in expression position in sloppy mode.

**Pull request closed without merging**
