### PR TITLE
Downstream tests should be executed using the latest Node.js 4.1.

### PR DESCRIPTION
**Pull request by ariya**
This is just a speculative attempt to fix a hit-and-miss issue on CircleCI running various downstream project test suites.

/cc @mikesherov @hzoo

### CODE REVIEW

**Comment by hzoo** [comment]
Yay? Not sure what was going on before

**Comment by ariya** [comment]
I'm still struggling to convince CircleCI to ignore the cache (Node.js 0.12 and other npm modules) and thereby to use Node.js 4.1.

**Comment by ariya** [comment]
Too bad Node.js will cause Istanbul tests to fail :-(
Looking at Istanbul's [Travis CI](https://travis-ci.org/gotwarlost/istanbul), seems that it is only tested well with 0.12.

**Comment by ariya** [comment]
@hzoo @mikesherov Same situation, Node.js 4 fails to run JSCS test: https://circleci.com/gh/jquery/esprima/136. You can reproduce this by cloning this repo and run:
```
npm i && npm run downstream
```

I'm closing this since clearly its speculative change doesn't have any meaningful effect.

**Pull request closed without merging**
