### PR TITLE
[ES6 Modules] ModuleSpecifier -> Literal

### PR DESCRIPTION
**Pull request by jeffmo**
Per https://github.com/jquery/esprima/issues/1077, this switches the harmony branch to use a `Literal` node for the 'source' property of `ImportDeclaration`s and `ExportDeclarations`.

(This PR is pending acceptance of https://github.com/estree/estree/pull/35/ , btw)

### CODE REVIEW

**Comment by nzakas** [comment]
:+1:

**Comment by ariya** [comment]
LGTM.

Nitpicky note: you might want to branch from your own fork, not this one. Otherwise we need to do a regular feature branch cleanup with other misc ramifications.

**Comment by jeffmo** [comment]
I can do that going forward.
(I was planning to just delete the branch once this got merged...but it's just as easy to do that on my own fork as well)

**Comment by caridy** [comment]
:+1:

**Comment by mikesherov** [comment]
@jeffmo, can you sign the CLA if you haven't?

**Comment by mikesherov** [comment]
FYI, I just landed estree/estree#35

**Comment by jeffmo** [comment]
CLA signed -- I think we're good here.

**Comment by mikesherov** [comment]
@jeffmo land at will then. Make sure commit message says `Closes gh-1086` as well. Thanks again!

**Comment by jeffmo** [comment]
https://github.com/jquery/esprima/commit/a9c08f911a15adcfa7182563b18a821490c5f61a

**Pull request closed without merging**
