### PR TITLE
fix #1328, fix comment missing in empty BlockStatement

### LINKED ISSUE #1328: comments missing bug in empty BlockStatement
early time, when es6 multiline feature is not available in node.js,  we always using `module:multiline` to write multiline strings(especially  sql),  it make code easy to read, code like:
```
var multiline = require('multiline');

var sql_xxxx = multiline(function () {
/*
SELECT
    columnes ...
FROM
    some_table
WHERE
    ..........
*/
});
```

but when we write testcase using  istanbul (which is writting in `esprima`, `escodegen`),  the comments in the anonymous function will be ate by esprima.

though esprima later support `attachComment` ( `leadingComments` and `tralingComments`) , but still missing the comments in the empty `BlockStatement`

### PR DESCRIPTION
**Pull request by fishbar**
after esprima apply this patch , escodegen also should be patched

### CODE REVIEW

**Comment by fishbar** [comment]
i'v sign the CLA using the same author info in git commit,  why still failed

**Comment by ariya** [comment]
@fishbar I'll take a look.

**Comment by kborchers** [comment]
The CLA checker is designed to look for 2 names to ensure real names are used. If you click the details link, it states "Suspicious name: fish Suspicious name: fishbar" which means the CLA was signed twice with the name fish and fishbar rather than a family name and a given name.

**Comment by michaelficarra** [comment]
@kborchers It's wrong to put restrictions on a person's name. See *[Falsehoods Programmers Believe About Names](http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/)*. This restriction violates the [jQuery code of conduct](https://jquery.org/conduct/): be welcoming.

**Comment by kborchers** [comment]
@michaelficarra I honestly agree with you and have made this argument multiple times. I will file an issue to have this check removed. The problem we run into is how do we verify this is a legal name on this legal document without getting a paper signature and photo copy of identification. From what I understand, this requirement was an attempt, and again I agree a bad one, at making sure the name was a legal name which we just may not be able to do and will have to take people's word for it.

**Pull request closed without merging**
