### PR TITLE
Release 2.6

### PR DESCRIPTION
**Pull request by ariya**

### CODE REVIEW

**Comment by ariya** [comment]
For detailed performance numbers, check #1308.

**Comment by mikesherov** [comment]
:+1:

**Comment by mikesherov** [comment]
Btw, for testing downstream projects, we may want to investigate the `dont-break` package.

**Comment by ariya** [comment]
For the badges, I don't have any strong opinion in favor or against it. If those badges seem to be too obnoxious, I'm fine with removing them.

**Comment by ariya** [comment]
> Btw, for testing downstream projects, we may want to investigate the dont-break package.

Good idea. I'll probably file it as an issue at some point but feel free to beat me to it.

**Comment by jasonLaster** [comment]
:+1:

**Pull request closed without merging**
