### PR TITLE
deep clone node when node.shorthand = true

### LINKED ISSUE #1755: Should create new Identifer Node when node.shorthand = true
## TestCase:

case 1:

```
let name = 'test';
let email = ''
let user = {name, email}
```

case 2:

```
let user = {name: 'test', email: 'abc@xxx.com'}
let {name, email} = user;
```
esprima parse  code into ast as following:

```
{
    "type": "ObjectExpression",
    "properties": [
        {
            "type": "Property",
            "key": {
                "type": "Identifier",
                "name": "name"
            },
            "computed": false,
            "value": {
                "type": "Identifier",
                "name": "name"
            },
            "kind": "init",
            "method": false,
            "shorthand": true
        },
        {
            "type": "Property",
            "key": { 
                "type": "Identifier",
                "name": "email"
            },
            "computed": false,
            "value": {
                "type": "Identifier",
                "name": "email"
            },
            "kind": "init",
            "method": false,
            "shorthand": true
        }
    ]
}
```

see the above AST tree, each property, the  Node(`key`) ===  the Node(`value`) , so when eshortten change the Identifier name into shortten chars,  bug cames

## Actual output:

```
let {a, b} = user;
```

## Expected

```
let {name:b,email:c}=a;
```

so esprima should clone the value Node from the key Node, instead of refer value Node to key Node

### PR DESCRIPTION
**Pull request by fishbar**
fix #1755

### CODE REVIEW

**Comment by michaelficarra** [comment]
LGTM.

**Comment by ariya** [comment]
Looks good @fishbar! Could also extend `api-tests.js` in the same style of commit d27d440c. Thanks!

**Comment by ariya** [comment]
On a second look, this change is superfluous. It is already implemented as part of PR #1520 (to fix #1519).

Thus, unfortunately I will have to revert it.

**Comment by fishbar** [comment]
it's  ok, : )

**Pull request closed without merging**
