### PR TITLE
Treat await as a reserved word when parsing as a module.

### LINKED ISSUE #1234: Treat await as a reserved word when parsing a module
See 11.6.2.2  on Future Reserved Words:

> `await` is only treated as a _FutureReservedWord_ when _Module_ is the goal symbol of the syntactic grammar.

### PR DESCRIPTION
**Pull request by ariya**
Fixes #1234

### CODE REVIEW

**Comment by jasonLaster** [comment]
Looks good. It still hurts me to see invalid syntax. Do you think an await() invocation example is needed?

**Comment by ariya** [comment]
> Do you think an await() invocation example is needed?

Technically speaking, it's not needed since it also goes to the production of a primary expression.

**Comment by michaelficarra** [comment]
@jasonLaster What invalid syntax?

@ariya I don't see any tests for tolerant mode. Otherwise, LGTM.

**Comment by ariya** [comment]
> I don't see any tests for tolerant mode

Good catch! Not sure why it wasn't there but it's now added.

**Comment by jasonLaster** [comment]
@ariya makes sense.

@michaelficarra I was referring fixtures in `/invalid_expression*.js` like `var await`.

**Pull request closed without merging**
