### PR TITLE
Release 2.1

### PR DESCRIPTION
**Pull request by ariya**

### CODE REVIEW

**Comment by ariya** [comment]
Note that I cherry-picked the commits to add 1.2.4 and 1.2.5 changes, for completeness.

**Comment by mikesherov** [comment]
Still need to convert default/rest properties to assigbmentPattern/restElement.

**Comment by mikesherov** [comment]
I'd like to give it a shot.

**Comment by ariya** [comment]
Rebased. No known regression (#1067 for details).

**Comment by mikesherov** [comment]
OK, so let's release Monday at 10AM PST?

On Sat, Mar 7, 2015 at 11:04 AM, Ariya Hidayat <notifications@github.com>
wrote:

> Rebased. No known regression (#1067
> <https://github.com/jquery/esprima/issues/1067> for details).
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/jquery/esprima/pull/1094#issuecomment-77695355>.
>



-- 
Mike Sherov

**Comment by ariya** [comment]
> so let's release Monday at 10AM PST?

Release party it will be!

**Pull request closed without merging**
