### PR TITLE
NumericLiteral, several improvements

### PR DESCRIPTION
**Pull request by Mr21**
issue related #1298

### CODE REVIEW

**Comment by michaelficarra** [comment]
Tests fail, but :+1: for the approach.

**Comment by Mr21** [comment]
Yeah I saw, but I didn't find the *how-to-run-tests* section, saw I started the PR to see the travis, now I have the commands to make in my shell ^^

**Comment by ariya** [comment]
Thanks for the contribution! Please create a ticket first in the issue tracker as usually there's more than just a simple optimization. Running the test is easy: `npm test`.

**Comment by Mr21** [comment]
@ariya, yeah it's very simple, thanks :)
Here the issue #1298, I will remake my commit to be okay with the tests.

**Comment by ariya** [comment]
Per the discussion at #1298, we will not pursue this further for now.

**Pull request closed without merging**
