### PR TITLE
Migrate to CircleCI 2.0

### PR DESCRIPTION
**Pull request by serima**
## Summary

- CircleCI runs speed up.
  - before 4:50 https://circleci.com/gh/jquery/esprima/677
  - after 2:58 https://circleci.com/gh/serima/esprima/tree/feature%2Fcircleci-20
    - If `node_modules` is cached it will be shortened by another 30 seconds
- Run parallel tests with node 6 and 8.

### CODE REVIEW

**Comment by ariya** [comment]
Hi @serima, thanks for looking into this. Can you do me a favor? Please just combine the two commits into a single one. Also, this Circle CI is being used to run [downstream tests](http://esprima.org/test/ci.html) which is known to be sensitive to the Node.js version, hence for maximum safety we shouldn't run it with Node.js v8.

**Comment by serima** [comment]
@ariya Okay. Thanks.

**Comment by serima** [comment]
@ariya  Since we did not need to use workflow, changed it to sequential processing and rebased.
Please review it again :)

**Comment by ariya** [comment]
LGTM, thank you @serima 👍

**Pull request closed without merging**
