### PR TITLE
Update test262 for ES2018+ features

### LINKED ISSUE #1995: Update test262 for ES2018+ features
Update test262 for ES2018+ features

### Notes

* [x] Update Whitelist as well

### PR DESCRIPTION
**Pull request by JosephPecoraro**
Fixes #1995

### CODE REVIEW

**Comment by JosephPecoraro** [comment]
@ariya Esprima update for test262! Are you available to review?

**Comment by JosephPecoraro** [comment]
Updated from a fresh checkout on a different machine so there is no noise.

**Comment by JosephPecoraro** [comment]
@ariya Should I continue to wait on these PRs, or is this repo no longer active?

**Comment by ariya** [comment]
Merged! Thanks @JosephPecoraro. Apologize for the delay, keep 'em coming.

**Pull request closed without merging**
