### PR TITLE
Adjust the error message for bad getter/setter arity

### LINKED ISSUE #1685: Adjust the error message for incorrect getter/setter arity
This is to align the description to follow [V8 error messages](https://chromium.googlesource.com/v8/v8/+/master/src/messages.h).

Test case for **setter method**:
```js
esprima.parse('x = { set y(a,b) { } }')
```

* Expected error message: "Setter must have exactly one formal parameter".
* Actual error message: "Unexpected token ,".

Test case for **getter method**:
```js
esprima.parse('x = { get y(a) { } }')
```

* Expected error message: "Getter must not have any formal parameters".
* Actual error message: "Unexpected identifier".

### PR DESCRIPTION
**Pull request by ariya**
Fix #1685

### CODE REVIEW

**Comment by hydroper** [comment]
@ariya Can you update the esprima parser used in the online demos?

**Comment by mikesherov** [comment]
@hydroper, the version on the demos gets updated when releases get cut.

**Comment by hydroper** [comment]
@mikesherov Unfortunately, it looks like it's not updated here: http://esprima.org/demo/parse.html?code=%5Cu%7B66%7Dor%20(%3B%3B)%3B

It should throw an error.

**Comment by ariya** [comment]
@hydroper That's not related to this PR (please don't do thread hijacking). The demo is only for stable releases, not for any development version (from master). It's updated once there is a 4.0 release.

**Comment by hydroper** [comment]
@ariya I could have issued that. I got it anyways.

**Pull request closed without merging**
