### PR TITLE
Downstream test: include redeyed.

### LINKED ISSUE #1377: Downstream test: include redeyed
Now that [redeyed](https://github.com/thlorenz/redeyed) is switched to upstream Esprima 2 (https://github.com/thlorenz/redeyed/pull/4), it should be included as part of the downstream project test. Due to its popularity, particularly via [cardinal](https://www.npmjs.com/package/cardinal), it is imperative not to regress redeyed.

### PR DESCRIPTION
**Pull request by ariya**
Closes #1377

### CODE REVIEW

**Comment by mikesherov** [comment]
:+1: congrats on the pickup ;-)

**Comment by ariya** [comment]
Unfortunately we can't verify this yet because CircleCI failed to complete the tests of JSCS. This seems to happen quite often with JSCS. I'm going to experiment with the change of the order so that JSCS becomes the last one.

**Comment by mikesherov** [comment]
I wonder why JSCS fails so often. Ping @hzoo

**Comment by hzoo** [comment]
Doesn't look like you can see any error messages? It just checks out master and then `(END)the build was canceled`? Or maybe I don't understand that output

**Comment by ariya** [comment]
@hzoo Better tracking it at #1247.

**Pull request closed without merging**
